variables:
  patch: $[counter('versioncounter', 31)]

name: 2.2.$(patch)

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Increase Vsix version'
  inputs:
    rootFolder: src
    extensionVersion: '$(Build.BuildNumber)'

- task: CopyFiles@2
  displayName: 'Copy Artifacts to Staging'
  inputs: 
    contents: '**\*.vsix'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(system.teamProject)'