variables:
  patch: $[counter('versioncounter', 31)]

name: 2.4.$(patch)

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@1
  displayName: 'Use Node CLI for Azure DevOps: v0.6.x'

- task: PowerShell@2
  displayName: 'Install PS_Modules'
  inputs:
    targetType: filePath
    filePath: ./Build.ps1

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  displayName: 'Build Vsix & Increase Vsix version'
  inputs:
    rootFolder: src
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true

- task: CopyFiles@2
  displayName: 'Copy Artifacts to Staging'
  inputs: 
    contents: '**\*.vsix'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(system.teamProject)'