variables:
  patch: $[counter('versioncounter', 7)]
  version: 1.0.$(patch)

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageVSTSExtension@1
  inputs:
    rootFolder: src
    extensionVersion: '$(version)'

- task: CopyFiles@2
  inputs:
    contents: '**\*.vsix' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: '$(system.teamProject)'