variables:
  patch: $[counter('versioncounter', 31)]

name: 2.5.$(patch)

steps:
- task: PowerShell@2
  displayName: 'Install PS_Modules'
  inputs:
    targetType: filePath
    filePath: ./Build.ps1

- task: PackageAzureDevOpsExtension@3
  displayName: 'Package vsix & Increase vsix version'
  name: 'packageStep'
  inputs:
    rootFolder: 'src'
    extensionVersion: '$(Build.BuildNumber)'
    updateTasksVersion: true

- task: PublishPipelineArtifact@1
  displayName: 'Publish vsix'
  inputs:
    publishLocation: pipeline
    targetPath: '$(packageStep.Extension.OutputPath)'
    artifact: 'vsix'